name: sample
on:
  push:
    branches:
    - main

jobs:
    testjob:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
        - name: script run
          run: |
                ls
                cat test.html  


            
    